const assert = require('node:assert/strict');
const {ControlQueue,readApiResponse} = require('../ui.js');
const deferred = () => {let resolve; const promise = new Promise(r => {resolve=r}); return {promise,resolve};};
(async () => {
  const response = (status, body) => ({status,ok:status===200,text:async()=>body});
  await assert.rejects(readApiResponse(response(503,'503: Service Unavailable')), /HTTP 503.*ikke JSON/);
  await assert.rejects(readApiResponse(response(200,'<html>Sign in</html>')), /ikke JSON/);
  await assert.rejects(readApiResponse(response(200,'null')), /ugyldigt/);
  await assert.rejects(readApiResponse(response(401,'{"error":"Authentication required"}')), /Authentication required/);
  assert.deepEqual(await readApiResponse(response(200,'{"revision":3,"mode":"music"}')), {revision:3,mode:'music'});
  const calls=[], responses=[], errors=[];
  const queue = new ControlQueue(patch => {calls.push(patch);const d=deferred();responses.push(d);return d.promise;}, () => {}, error => errors.push(error));
  queue.accept({mode:'restore',revision:0},0);
  const staleEpoch=queue.epoch;
  const first=queue.change({mode:'chase'});
  queue.change({color:'#00ff00'});
  queue.change({brightness:45});
  assert.equal(queue.accept({mode:'restore',revision:0},staleEpoch),false);
  assert.equal(queue.state.mode,'chase');
  assert.equal(calls.length,1);
  responses[0].resolve({revision:1});
  await new Promise(resolve => setImmediate(resolve));
  assert.deepEqual(calls[1],{color:'#00ff00',brightness:45});
  assert.equal(calls[1].mode,undefined,'changing color must not select restore');
  responses[1].resolve({revision:2});await first;
  assert.equal(queue.accept({mode:'restore',revision:1},queue.epoch),false);
  assert.equal(queue.state.mode,'chase');
  const off=queue.change({mode:'off'});
  queue.change({mode:'chase'});
  responses[2].resolve({revision:3});await new Promise(resolve=>setImmediate(resolve));
  assert.deepEqual(calls[3],{mode:'chase'});
  responses[3].resolve({revision:4});await off;
  assert.equal(queue.state.mode,'chase');assert.deepEqual(errors,[]);
  console.log('Stale polling, rapid green color change and off → chase regression checks passed');
})().catch(error => {console.error(error);process.exitCode=1});
